name: "Push scaladoc on gh-pages"

on:
  push:
    branches:
      - dev
  release:
    types:
      - published

jobs:
  push-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ./.github/actions

    - name: Build scaladoc
      run: sbt clean compile unidoc

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/scala-2.12/unidoc
        target-folder: ${{ github.ref_name }}
