name: Scala CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: ./.github/actions

  compile:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - run: sbt "+test:compile"

  test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - run: sbt "++2.11.12; testWithoutFormal"

  formal:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - run: sbt "++2.11.12; testFormal"

  scaladoc:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - run: sbt unidoc

  fmt-lint:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.ref != 'refs/heads/dev'

    steps:
    - name: Fetch dev to be able to check only modified files
      run: |
        git fetch --depth=1 origin dev
        git branch dev origin/dev
    - name: Setup annotations
      run: echo "::add-matcher::.github/matcher.json"
    - name: Check formatting and pass
      run: bash .github/checkfmt.bash
